# Generated by Django 5.1.6 on 2025-04-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
